apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-db-store
spec:
  provider:
    vault:
      server: "http://vault-active.vault:8200" # Địa chỉ service vault
      path: "database" # Path của database engine
      version: "v1"
      auth:
        kubernetes:
          mountPath: "kubernetes" # Phải khớp với lúc 'vault auth enable'
          role: "webapp-role"     # Phải khớp với tên role
          serviceAccountRef:
            name: external-secrets       # SA mà App/ESO dùng
            namespace: vault
