apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-sync
  namespace: demo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-db-store   # Trỏ tới đúng SecretStore "vault-backend" đã tạo trước đó
    kind: ClusterSecretStore
  target:
    name: postgres-secret # TÊN K8S SECRET MÀ ESO SẼ TẠO RA TRÊN KUBERNETES
    creationPolicy: Owner

  dataFrom:
    - extract:
        key: database/creds/webapp-role
#  data:
#  - secretKey: POSTGRES_USER      # Key trong K8s Secret
#    remoteRef:
#      key: database/creds/webapp-role
#      property: username  # Lấy giá trị 'username' từ Vault

#  - secretKey: POSTGRES_PASSWORD  # Key trong K8s Secret
#    remoteRef:
#      key: database/creds/webapp-role
#      property: password  # Lấy giá trị 'password' từ Vault
