apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: demo
  labels:
    app: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
        - name: frontend-container
          image: peidhhn/frontend-nodejs:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: "http://backend-service:5000"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring:4318"
            - name: OTEL_SERVICE_NAME
              value: "backend-nodejs"
