apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-minio
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/backup"
  claimRef:
    name: data-minio-0
    namespace: demo
