---
- name: Config for all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Config for all master nodes
  hosts: masters
  become: yes
  roles:
    - masters

- name: config for all worker nodes
  hosts: workers
  become: yes
  roles:
    - workers
