# --- STAGE 1: Build Stage ---
FROM node:20.11.1-bookworm AS builder

WORKDIR /app

# Copy package files to reuse Docker Layer Cache for node_modules
COPY package*.json ./

# Install dependencies 
RUN npm ci

#Copy source code
COPY . .

# --- STAGE 2: Runtime Stage ---
FROM node:20.11.1-bookworm-slim

WORKDIR /app

## Copy needed files from stage builder
COPY --from=builder /app .

USER node

EXPOSE 3000

CMD ["node", "frontend.js"]
