[masters]
master-cp1 ansible_host=10.10.0.199

[workers]
worker-node1 ansible_host=10.10.0.101
worker-node2 ansible_host=10.10.0.102
worker-node3 ansible_host=10.10.0.103


[all:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/id_rsa

