tempo:
  multitenancyEnabled: false

  searchEnabled: true

  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo-data
        endpoint: svc-minio.demo.svc.cluster.local:9000
        insecure: true
        forcepathstyle: true

  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true

  extraEnvFrom:
    - secretRef:
        name: tempo-minio-secret

  ingester:
    #replicas: 1
    # Ép flush dữ liệu sau mỗi 5 phút hoặc khi đạt 10MB (tùy điều kiện nào đến trước)
    max_block_duration: 5m
    #max_block_bytes: 10485760
#  querier:

#  queryFrontend:

