apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-pri-new
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pg-pv-pri"
  claimRef:
    name: pg-cluster-new-1
    namespace: demo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-rep1-new
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pg-pv-rep1"
  claimRef:
    name: pg-cluster-new-2
    namespace: demo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-pv-rep2-new
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/pg-pv-rep2"
  claimRef:
    name: pg-cluster-new-3
    namespace: demo
