deploymentMode: SimpleScalable

minio:
  enabled: false

loki:
  auth_enabled: false # Tắt multi-tenancy

  # Ép Loki không dùng PVC cho storage cục bộ (vì đã có S3)
  commonConfig:
    replication_factor: 1

  # Cấu hình storage trỏ về S3 MinIO
  storage:
    filesystem:
      enabled: false
    type: "s3"
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: svc-minio.demo.svc.cluster.local:9000
      s3ForcePathStyle: true
      insecure: true
      region: "us-east-1"
      #accessKeyId: loki
      #secretAccessKey: loki12345

  # Cấu hình Schema v13 cho TSDB (chuẩn mới nhất, lưu cả index và chunks vào S3)
  schemaConfig:
    configs:
      - from: "2024-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

# Define các thành phần cơ bản Read, Write, Backend
write:
  extraEnvFrom:
    - secretRef:
        name: loki-minio-secret
  replicas: 1
  persistence:
    size: 1Gi

read:
  extraEnvFrom:
    - secretRef:
        name: loki-minio-secret
  replicas: 1

backend:
  extraEnvFrom:
    - secretRef:
        name: loki-minio-secret
  replicas: 1
  persistence:
    size: 1Gi

chunksCache:      # Cache log chunk đã đọc từ MinIO, giữ lại trong RAM/Disk query sau sẽ nhanh hơn
  enabled: false

resultsCache:     # Cache kết quả query, query giống hệt lặp lại trả cache luôn
  enabled: false
