global:
  domain: argocd.lab.local
configs:
  params:
    server.insecure: true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: argocd.lab.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - argocd.lab.local
        secretName: argocd-server-tls
    annotations:
      cert-manager.io/cluster-issuer: selfsigned
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
