apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: client-app-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "client-app"
      useAnnotations: true
