apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: API_HOST
              value: {{ .Values.env.apiHost | quote }}
            - name: USER_INTERVAL
              value: {{ .Values.env.userInterval | quote }}
            - name: ORDER_INTERVAL
              value: {{ .Values.env.orderInterval | quote }}
            - name: PAYMENT_INTERVAL
              value: {{ .Values.env.paymentInterval | quote }}
