apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pg-cluster-new  # Pods: pg-cluster-new-[1;2;3], Services: pg-cluster-new-[r,ro,rw]
  namespace: demo
spec:
  instances: 3           # 1 Primary + 2 Replicas
  imageName: ghcr.io/cloudnative-pg/postgresql:15

  storage:
    size: 1Gi
    pvcTemplate:
      accessModes:
        - ReadWriteOnce

  # 1. Khai báo nguồn dữ liệu ngoại vi (Minio)
  externalClusters:
    - name: old-cluster-source # Tên của cluster GỐC (nơi tạo ra bản backup)
      barmanObjectStore:
        destinationPath: s3://cnpg-bucket/
        endpointURL: http://svc-minio:9000
        serverName: "pg-cluster" # auto scan in path s3://cnpg-bucket/pg-cluster to search "backup.info"
        s3Credentials:
          accessKeyId:
            name: minio-secret # Dùng admin console
            key: username
          secretAccessKey:
            name: minio-secret
            key: password

  # 2. Chỉ định restore từ nguồn này
  bootstrap:
    recovery:
      source: old-cluster-source
#      Không define sẽ backup trạng thái mới nhất khi cluster còn thở
#      recoveryTarget:
#        targetTime: "2026-05-04 11:52:00"    # 20260504T115201 -> 2026-05-04 11:52:01 + thêm 2-3 phút cho chắc
#        backupID: "20260505T092839"
#      backup:
#        name: "20260504T115201" # Tên bản backup muốn restore
#        -> Không work vì xóa toàn bộ cluster nên các Object Backup cũng bị xóa 
#        nó tìm demo/20260504T115201 trong K8s thay vì trong MinIO -> dùng targetTime 

  # 3. (Tùy chọn) Cấu hình để cluster mới này tiếp tục backup
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-bucket/
      endpointURL: http://svc-minio:9000
      s3Credentials:
        accessKeyId:
          name: backup-secret  # Dùng user backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: backup-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
