{
 "title": "K8S APP OBSERVABILITY - FRONTEND & BACKEND",
 "tags": [
  "kubernetes",
  "otel",
  "devops"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Rate (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{exported_job=~\"(frontend|backend)-nodejs\"}[5m])) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Latency P95 (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{exported_job=~\"(frontend|backend)-nodejs\"}[5m])) by (le, exported_job))",
     "legendFormat": "{{exported_job}} - P95"
    }
   ]
  },
  {
   "title": "HTTP 500 Error Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_duration_milliseconds_count{http_status_code=\"500\"}) by (exported_job)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"demo\", pod=~\"(frontend|backend).*\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "RAM Usage (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{namespace=\"demo\", pod=~\"(frontend|backend).*\", container!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Database Write Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"pg-cluster.*\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Database Read Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"pg-cluster.*\", container!=\"\"}[5m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Application Logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{exporter=\"OTLP\"} | json | line_format \"{{.body}}\""
    }
   ]
  }
 ]
}