replicaCount: 1

image:
  repository: peidhhn/client-app
  tag: latest
  pullPolicy: IfNotPresent

app:
  name: metrics-client

env:
  apiHost: http://metrics-app
  userInterval: "2"
  orderInterval: "3"
  paymentInterval: "5"
