apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: USER_MIN
              value: {{ .Values.env.userMin | quote }}
            - name: USER_MAX
              value: {{ .Values.env.userMax | quote }}
            - name: ORDER_MIN
              value: {{ .Values.env.orderMin | quote }}
            - name: ORDER_MAX
              value: {{ .Values.env.orderMax | quote }}
            - name: PAYMENT_MIN
              value: {{ .Values.env.paymentMin | quote }}
            - name: PAYMENT_MAX
              value: {{ .Values.env.paymentMax | quote }}
